theme: jekyll-theme-minimal
title: WorkflowHub project
email: info@esciencelab.org.uk
description: > 
  Project pages for developing and running WorkflowHub, 
  a registry of scientific workflows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://about.workflowhub.eu" # the base hostname & protocol for your site
github_username:  workflowhub-eu
encoding: UTF-8
permalink: pretty

logo: /logo/workflowhub-square.svg
markdown: CommonMarkGhPages

plugins:
  - jekyll-redirect-from  
