title: WorkflowHub project

description: > 
  Project pages for developing and running WorkflowHub, 
  a registry of scientific workflows.

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.5.3

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: documentation
  -
    scope:
      path: "about"
      type: "pages"
    values:
      layout: "page"
      sidebar: about

theme_variables: 
  theme_color: 1f8787

plugins:
  - jekyll-redirect-from  