title: WorkflowHub project

email: info@esciencelab.org.uk
description: > # this means to ignore newlines until "baseurl:" 
  Project pages for developing and running WorkflowHub, 
  a registry of scientific workflows.

remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@1.1.2
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main

theme_variables: 
  theme_color: 1f8787
